# Generated by Django 3.1.1 on 2020-09-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pumpInstData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rms_id', models.CharField(blank=True, max_length=50, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('flow_lph', models.IntegerField(blank=True, null=True)),
                ('power_kwh', models.IntegerField(blank=True, null=True)),
                ('voltage_pump', models.FloatField(blank=True, null=True)),
                ('current_pump', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
