# Generated by Django 3.1.1 on 2020-09-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(blank=True, max_length=50, null=True)),
                ('System_RID_No', models.CharField(blank=True, max_length=30, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('RunTime_Hrs', models.FloatField(blank=True, null=True)),
                ('Water_Discharge_Lts', models.FloatField(blank=True, null=True)),
                ('Pump_Consumption_KWH', models.FloatField(blank=True, null=True)),
                ('Inverter_Input_KWH', models.FloatField(blank=True, null=True)),
                ('Inverter_Output_KWH', models.FloatField(blank=True, null=True)),
                ('Total_KWH_Generation', models.FloatField(blank=True, null=True)),
                ('Gross_KWH', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pumpinstdata',
            name='power_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
