# Generated by Django 3.1.1 on 2020-09-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200927_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Code', models.CharField(blank=True, max_length=30, null=True)),
                ('Test_Date', models.DateTimeField(blank=True, null=True)),
                ('Flow', models.FloatField(blank=True, null=True)),
                ('Power', models.FloatField(blank=True, null=True)),
                ('Voltage', models.FloatField(blank=True, null=True)),
                ('Currents', models.FloatField(blank=True, null=True)),
                ('Temperature', models.FloatField(blank=True, null=True)),
                ('RPM', models.IntegerField(blank=True, null=True)),
                ('ONStat', models.CharField(blank=True, max_length=10, null=True)),
                ('RunStat', models.CharField(blank=True, max_length=10, null=True)),
                ('IsAlert', models.IntegerField(blank=True, null=True)),
                ('IsFault', models.IntegerField(blank=True, null=True)),
                ('Panel1_Voltage', models.FloatField(blank=True, null=True)),
                ('Panel1_Current', models.FloatField(blank=True, null=True)),
                ('DC_Power', models.FloatField(blank=True, null=True)),
                ('Grid_Frequency', models.FloatField(blank=True, null=True)),
                ('U_Voltage', models.FloatField(blank=True, null=True)),
                ('V_Voltage', models.FloatField(blank=True, null=True)),
                ('W_Voltage', models.FloatField(blank=True, null=True)),
                ('U_Current', models.FloatField(blank=True, null=True)),
                ('V_Current', models.FloatField(blank=True, null=True)),
                ('W_Current', models.FloatField(blank=True, null=True)),
                ('Temperature1', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
