# Generated by Django 3.1.1 on 2020-09-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_ind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ind',
            name='Site_Code',
        ),
        migrations.AddField(
            model_name='ind',
            name='rms_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.pumpinstdata'),
        ),
    ]
