# Generated by Django 3.1.1 on 2020-09-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200927_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ind',
            old_name='rms_id',
            new_name='Site_Code',
        ),
    ]
