# Generated by Django 3.1.1 on 2020-09-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200927_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dd',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ind',
            name='Site_Code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
