# Generated by Django 3.1.1 on 2020-09-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200928_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dd',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
