# Generated by Django 3.1.1 on 2020-09-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200928_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ss1',
            fields=[
                ('Proj', models.CharField(blank=True, max_length=50, null=True)),
                ('RID_No', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Date1', models.DateTimeField(blank=True, null=True)),
                ('Total_KWH1', models.FloatField(blank=True, null=True)),
                ('Gross_KWH1', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
